preload = /home/kaio/Imagens/wallpapers/vergil2_upscayl_4x_upscayl-standard-4x.png

wallpaper {
    monitor = eDP-1
    path = /home/kaio/Imagens/wallpapers/vergil2_upscayl_4x_upscayl-standard-4x.png
}
